name: bhjet_tutorial
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools
  - compilers
  - cmake
  - make
  - gsl
  - llvm-openmp
  - nanobind
  - scikit-build-core
  - numpy
  - scipy
  - pandas
  - matplotlib
  - astropy
  - jupyterlab
  - ipykernel
  - ipywidgets
  - ipympl
