name: bhjet-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools
  - numpy
  - scipy
  - matplotlib
  - astropy
  - gammapy=2.0
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - ipympl
  - nbclient
  - scikit-build-core
  - nanobind
